name: Deploy Webapp to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: "deploy pages"
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read    # to read the repository

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Projects Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node Dependencies
        run: npm ci

      - name: Build TypeScript Project
        run: npm run build

      - name: Configure GitHub Pages Deployment
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

  deploy:
    needs: build

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy Webapp to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Remove Generated Artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: github-pages
          failOnError: false
